spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <Your email id>
    password: <Password from email security>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true